
GET http://localhost:3000/ HTTP/1.1

###
GET http://localhost:3000/job HTTP/1.1


GET https://fakestoreapi.com/products HTTP/1.1


##
POST https://fakestoreapi.com/products HTTP/1.1
content-type: application/json

{
  "id": 0,
  "title": "string",
  "price": 0.1,
  "description": "string",
  "category": "string",
  "image": "http://example.com"
}