version: '3.8'

services:
  # app:
  #   build: .
  #   container_name: devotel-job-api
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis

  db:
    image: postgres:16-alpine
    container_name: devotel-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devotel_job
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_net

  cache:
    image: redis:7.2
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - local_net

volumes:
  postgres_data:
  redis_data:

networks:
  local_net:
    driver: bridge
